from .nodes import NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS
from .nodes_video import NODE_CLASS_MAPPINGS as VIDEO_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VIDEO_NODE_DISPLAY_NAME_MAPPINGS
from .nodes_vision import NODE_CLASS_MAPPINGS as VISION_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as VISION_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**IMAGE_NODE_CLASS_MAPPINGS, **VIDEO_NODE_CLASS_MAPPINGS, **VISION_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**IMAGE_NODE_DISPLAY_NAME_MAPPINGS, **VIDEO_NODE_DISPLAY_NAME_MAPPINGS, **VISION_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
